### ISSUE TITLE
Bug is causing this app to turn my phone off?

### ISSUE THREAD

**Issue by CMahaff** [project-voodoo/simple_carrieriq_detector_app#4]
I know this sounds strange, I've never heard of such a thing. I'm running Android 2.2 with Motoblur. Non-rooted. Using GO EX and a lockscreen changer but nothing too fancy. When I run the app it opens and starts "checking" for CIQ then the phone turns off. I don't think it's a fluke because I turned my phone on and tried again and the same thing happened. Screen goes black and I have to turn it on again.

Also left this in a review of the app on the market.

I have no idea what could be going on. I am learning to be a developer so if need be I can take the source and see if I get any errors in LogCat. Unless I'm alone in experiencing this issue.

**Comment by supercurio** [comment]
Hi!
Thanks for the report. This commit https://github.com/project-voodoo/simple_carrieriq_detector_app/commit/14c67ccd99a2f922145dc261fd11131b1a51cb25 should fix the issue you describe here.

If not, please specify the device we're talking about ;)

**Comment by CMahaff** [comment]
Ah so sorry! Phone is the Motorola Defy. I'll have to try it out then and see. Thanks for the response!

**Comment by supercurio** [comment]
Defy too! Meh :D
It's not covered then. Could you paste here this device /system/build.prop ?

**Comment by CMahaff** [comment]
I'm afraid I'm not rooted. Unless there is someway to get this without rooting the device I'm afraid I can't help :/

**Comment by supercurio** [comment]
adb shell cat /system/build.prop, no root needed

**Comment by CMahaff** [comment]
Sorry I'm sure you can tell that I'm a bit of a noob.

Here it is: http://dl.dropbox.com/u/2151275/prop.txt

**Comment by supercurio** [comment]
Alright thanks starting with 1.3 now on market version the issue should be solved ;)
Please confirm it works for you.

**Comment by CMahaff** [comment]
Works now, and CIQ wasn't found. Thanks a bunch!

**Comment by supercurio** [comment]
You're welcome ;)
